inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  Include:
    - "app/**/*.rb"

Layout/LineLength:
  Enabled: true
  Max: 120
  AllowHeredoc: true
  AllowURI: true

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: new_line

Layout/BlockAlignment:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyle: space

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true
